version: "3.6"

services:
  research:
    build: .
    volumes:
      - .:/opt/research
      - /tmp/.X11-unix:/tmp/.X11-unix
    working_dir: /opt/research
    devices:
      - /dev/snd:/dev/snd
    environment:
      DISPLAY: unix$DISPLAY
    tty: true
    # command: python resize.py
